insert into country(id,name,alternate_name,description) values (1,"Nederland","Nederland","Nederland is een van de landen binnen het Koninkrijk der Nederlanden. Nederland ligt voor het overgrote deel in het noordwesten van Europa, aan de Noordzee. Naast het Europese deel zijn er nog de drie bijzondere gemeenten in de Caribische Zee, die ook wel Caribisch Nederland worden genoemd. Europees Nederland wordt in het zuiden begrensd door België, langs de oostgrens door Duitsland en aan west- en noordzijde door de zee. De hoofdstad van Nederland is Amsterdam, de regeringszetel is Den Haag.");
insert into country(id,name,alternate_name,description) values (2,"België","België","België, officieel het Koninkrijk België, is een West-Europees land dat aan de Noordzee ligt en aan Nederland, Duitsland, Luxemburg en Frankrijk grenst. Het land is 30.528 vierkante km groot en heeft een bevolking van meer dan 11,7 miljoen inwoners (ruim 6,9 miljoen in het Vlaams Gewest, 3,6 miljoen  in het Waals Gewest en 1,2 miljoen in het Brussels Hoofdstedelijk Gewest). Brussel is de hoofdstad van België en tevens het bestuurlijk centrum van de Europese Unie en de NAVO.");
insert into country(id,name,alternate_name,description) values (3,"Duitsland","Deutschland","De Bondsrepubliek Duitsland (BRD) (Duits: Bundesrepublik Deutschland), kortweg Duitsland (Duits: Deutschland), is een land in West- en of Centraal-Europa. Het heeft een grondgebied van 357.022 vierkante km en grenst in het noorden aan de Oostzee, de Noordzee en Denemarken, in het oosten aan Polen en Tsjechië, in het zuiden aan Oostenrijk en Zwitserland en in het westen aan Frankrijk, Luxemburg, België en Nederland. Duitsland heeft met 83.222.442 inwoners (30 september 2021) de grootste bevolking van alle landen in de Europese Unie. De hoofdstad en grootste stad van het land is Berlijn.");
insert into country(id,name,alternate_name,description) values (4,"Luxemburg",NULL,NULL);
insert into country(id,name,alternate_name,description) values (5,"Frankrijk",NULL,NULL);
insert into country(id,name,alternate_name,description) values (6,"Spanje",NULL,NULL);
insert into country(id,name,alternate_name,description) values (7,"Portugal",NULL,NULL);
insert into country(id,name,alternate_name,description) values (8,"Italie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (9,"Monaco",NULL,NULL);
insert into country(id,name,alternate_name,description) values (10,"Liechtenstein",NULL,NULL);
insert into country(id,name,alternate_name,description) values (11,"Oostenrijk",NULL,NULL);
insert into country(id,name,alternate_name,description) values (12,"Zwitserland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (13,"Groot-Britannie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (14,"Ierland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (15,"Denemarken",NULL,NULL);
insert into country(id,name,alternate_name,description) values (16,"Zweden",NULL,NULL);
insert into country(id,name,alternate_name,description) values (17,"Noorwegen",NULL,NULL);
insert into country(id,name,alternate_name,description) values (18,"Finland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (19,"Polen",NULL,NULL);
insert into country(id,name,alternate_name,description) values (20,"Hongarije",NULL,NULL);
insert into country(id,name,alternate_name,description) values (21,"Tjechie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (22,"Slowakije",NULL,NULL);
insert into country(id,name,alternate_name,description) values (23,"Slovenie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (24,"Estland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (25,"Letland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (26,"Litouwen",NULL,NULL);
insert into country(id,name,alternate_name,description) values (27,"Griekenland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (28,"Cyprus",NULL,NULL);
insert into country(id,name,alternate_name,description) values (29,"Malta",NULL,NULL);
insert into country(id,name,alternate_name,description) values (30,"Servie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (31,"Montenegro",NULL,NULL);
insert into country(id,name,alternate_name,description) values (32,"Albanie",NULL,NULL);
insert into country(id,name,alternate_name,description) values (33,"Kosovo",NULL,NULL);
insert into country(id,name,alternate_name,description) values (34,"Ijsland",NULL,NULL);
insert into country(id,name,alternate_name,description) values (35,"Canada",NULL,NULL);
insert into country(id,name,alternate_name,description) values (36,"Verenigde Staten",NULL,NULL);